services:
  eureka-service:
    image: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend

  customer:
    image: customer
    build:
      context: ./customer
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      - postgres
      - eureka-service
      - fraud
    networks:
      - backend

  fraud:
    image: fraud
    build:
      context: ./fraud
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      - postgres
      - eureka-service
    networks:
      - backend

  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      - eureka-service
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
