spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
server:
  port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"