server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: fraud
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        default_schema: public
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true